### ISSUE TITLE
Implement access token refreshing

### ISSUE THREAD

**Issue by mats-claassen** [IDme/ID.me-WebVerify-SDK-iOS#7]
The SDK should handle the refreshing of the access token without external input.

The access token refreshing can happen in different ways and depends on the endpoints provided by the backend.

At first the options would be:
* The server sends a new token with every response thus refreshing the token with every request.
* The SDK periodically refreshes the access token (certain time before it expires)
* The SDK lets the access token expire and refreshes it for the first request after its expiration time.

We need your comments here @sdownie

**Comment by m-revetria** [comment]
Something about the first option

> The server sends a new token with every response thus refreshing the token with every request.

API calls will be done outside the SDK, so the refreshed token get from the API call won't be updated in the SDK. So, we have to think on how the SDK can get notified with the just refreshed token. On the other hand, I think is a good approach refreshing the token automatically on each request. This seems to be even more useful if we take into account that the token may have a short lifetime

**Comment by sdownie** [comment]
Closing this issue for now since OAuth implicit flow can't support token refreshing
